
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Circle = 14;
  public static final int CanvasAddFigure = 10;
  public static final int Canvas = 9;
  public static final int coma = 8;
  public static final int CodeDraw = 2;
  public static final int Square = 13;
  public static final int keyOpen = 3;
  public static final int Line = 12;
  public static final int EOF = 0;
  public static final int keyClose = 4;
  public static final int CanvasBackground = 11;
  public static final int pointComa = 7;
  public static final int parentOpen = 5;
  public static final int error = 1;
  public static final int parentClose = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CodeDraw",
  "keyOpen",
  "keyClose",
  "parentOpen",
  "parentClose",
  "pointComa",
  "coma",
  "Canvas",
  "CanvasAddFigure",
  "CanvasBackground",
  "Line",
  "Square",
  "Circle"
  };
}

